### PR TITLE
Adding new sensor "last update" to retrieve the date and time from the last connection to Ecowater server

### PR DESCRIPTION
**Pull request by figorr**
Version 3.3.1
- New "last update" sensor: It retrieves the data and time the integration connects to the Ecowater server.
- Some minor changes. OUT OF SALT ON ... now gives the data d/m/Y instead Y/m/d when date format at setup is dd/mm/yyyy
- Update Readme file to show the current version and changelog.
- Update manifest.json to show version 3.3.1

### CODE REVIEW

**Comment by heisenberg2980** [comment]
@barleybobs is there anything stopping this PR from being merged?

**Comment by figorr** [comment]
Sorry. I am going to close this pull request. I need to test a bit more the "Last Update" sensor code. Because I saw there are some situations where the API is showing the device is "Online" but it is not receiving new data. I looks like the API is blocking the mobile app and the integration because I reached the limit API Calls. I can see the Softener had new data but it is not updating to the Ecowater Cloud until I did a powercycle of the Softener.

**Comment by heisenberg2980** [comment]
@figorr that is exactly the reason to have this new sensor "Last Update". The idea is to have a sensor that is only updated when the integration has been able to update data from Ecowater servers successfully, so when the ecowater servers block the app, the sensor will show that the last update was for example an hour ago, and we can create an automation to powercycle the softener.

This sensor "Last Update" should be updated every time Home Assistant is able to call the ecowater servers, and it should NOT be updated if the call to ecowater fails.

**Comment by figorr** [comment]
Sorry @heisenberg2980, I didn't explain myself well. The "Last Update" sensor wasn't working as I expected and in the case I described above... when the integration crashed... it kept updating the date and time as if it hadn't crashed.

Over this weekend I've been playing around with a forked version. I've introduced some changes. The problem is that I haven't only updated the "Last Update" sensor... I've also been playing around with translating the name of the sensors and I've introduced the Spanish translation (es.json). I've also corrected the way the date format is displayed in the "Out of Salt On" sensor when the date format chosen in the setup is "dd/mm/yyyy", so now gives the data d/m/Y instead Y/m/d.

So I've made a lot of changes. But if you dare... you can try the beta that I've been testing today. It seems to work fine. I haven't seen any errors in the log. And the "Last Update" sensor is updating fine, although I must also say that the API hasn't failed today, :)

You can find the beta (Beta v3.4.4.B01) under "Releases" at the forked repository. You just need to download the beta and replace the content of the ecowater_softener folder. This is like a manual installation.

[homeassistant-ecowater-softener forked version](https://github.com/figorr/homeassistant-ecowater-softener/tree/test)

As I said this beta includes a lot of changes I made during the weekend. Please don't take in mind what readme says about creating an input_number and an input_button. I was also playing about dinamically changing the timedelta (time between scans) without having to reload the integration of HA but It didn't work, so I removed this part of the code. I need to think about it a bit more. And if finally I can find a solution I will send a pull request to @barleybobs, so he can decide if it could be useful or not.

Always, before start testing anything ... I recommend you to do a couple of things.
1. Make a copy of the entire integration folder, i.e. the "ecowater_softener" folder inside custom_components.
2. Make a full backup of Home Assistant.

So, if any errors occur or you just don't like the changes, you can always start with option 1 and restart the contents of the ecowater_softener folder back to its place and restart HA. Or if things get worse... you can go for option 2 and restore the HA backup you did.

As I said, in my case everything went well. I didn't see any error at log and the integration was loaded OK.

If the "Last Update" sensor works as expected ... maybe @barleybobs can include it in the future ... I will send a new pull request, but I think it is too early ... I need a bit more testing. I deleted the pull request for this reason.

**Pull request closed without merging**
